language: java
jdk: openjdk13
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./gradlew build
after_script:
  - export JACOCO_SOURCE_PATH=eval-code-quality/src/main/java/
  - ./cc-test-reporter format-coverage ./eval-code-quality/build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
